default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: access_by_ip_development
  host: localhost

test:
  <<: *default
  database: access_by_ip_test
  host: localhost

production:
  <<: *default
  database: access_by_ip_production
  username: access_by_ip
  password: <%= ENV['ACCESS-BY-IP_DATABASE_PASSWORD'] %>
